In [1]:
import numpy as np

In [2]:
gravity = 9.8

num_springs=int(input("How many springs are in your system?"))

How many springs are in your system? 4


In [3]:
# receive mass inputs

mass_list = []
for i in range(num_springs - 1):
    mass = int(input('What is mass ' + str(i + 1) + '?'))
    mass_list.append(mass)

What is mass 1? 3
What is mass 2? 2
What is mass 3? 5


In [4]:
c_list = []
for i in range(num_springs):
    c = int(input('What is the spring constant of spring ' + str(i + 1) + '?'))
    c_list.append(c)

What is the spring constant of spring 1? 2
What is the spring constant of spring 2? 1
What is the spring constant of spring 3? 4
What is the spring constant of spring 4? 2


In [5]:
force_matrix = np.array(mass_list) * 9.8
force_matrix

array([29.4, 19.6, 49. ])

In [6]:
c_matrix = np.zeros((num_springs, num_springs), int)
np.fill_diagonal(c_matrix, c_list)
c_matrix

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 2]])

In [18]:
# fixed - fixed system

# generate difference matrix
A = np.zeros((num_springs, num_springs - 1))
np.fill_diagonal(A, 1)
np.fill_diagonal(A[1:], -1)
A

array([[ 1.,  0.,  0.],
       [-1.,  1.,  0.],
       [ 0., -1.,  1.],
       [ 0.,  0., -1.]])

In [29]:
At = A.transpose()

At = np.matrix(At)
A = np.matrix(A)
c_matrix = np.matrix(c_matrix)
force_matrix = np.matrix(force_matrix)

In [27]:
k = At * c_matrix * A

In [28]:
k

matrix([[ 3., -1.,  0.],
        [-1.,  5., -4.],
        [ 0., -4.,  6.]])

In [33]:
kinv = np.linalg.inv(k)

In [36]:
u = force_matrix * kinv

In [37]:
u

matrix([[20.14444444, 31.03333333, 28.85555556]])

In [39]:
e = A*u.transpose()

In [40]:
e

matrix([[ 20.14444444],
        [ 10.88888889],
        [ -2.17777778],
        [-28.85555556]])

In [42]:
w = c_matrix*e

In [43]:
w

matrix([[ 40.28888889],
        [ 10.88888889],
        [ -8.71111111],
        [-57.71111111]])

In [44]:
At * w

matrix([[29.4],
        [19.6],
        [49. ]])

In [46]:
force_matrix

matrix([[29.4, 19.6, 49. ]])